language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"  
  - "pypy3"

install:
  pip install requests

script:
  - export TEST_MODE=TRAVIS
  - export AT_HOSTNAME=$AT_HOSTNAME
  - export AT_ENCRYPTION_KEY=$AT_ENCRYPTION_KEY
  - export AT_TRANSITION_KEY=$AT_TRANSITION_KEY
  - export AT_SALT=$AT_SALT
  - python test/test_authtoken.py